version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    main: ./cmd/fleeting-plugin-cloudscale

    # Store the results in a way that is compatible with fleeting-artifact
    # See https://gitlab.com/gitlab-org/fleeting/fleeting-artifact
    binary: "{{ .Os }}/{{ .Arch }}/plugin"
    no_unique_dist_dir: true

    # Configure the linker flags required for version information
    ldflags:
      - -s -w
      - -X github.com/cloudscale-ch/fleeting-plugin-cloudscale.VERSION={{.Version}}
      - -X github.com/cloudscale-ch/fleeting-plugin-cloudscale.REVISION={{.ShortCommit}}
      - -X github.com/cloudscale-ch/fleeting-plugin-cloudscale.REFERENCE={{.Tag}}
      - -X github.com/cloudscale-ch/fleeting-plugin-cloudscale.BUILT={{.Date}}

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
