name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Create release with goreleaser
        run: go tool goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container with fleeting-artifact
        run: |
          echo "$QUAY_IO_TOKEN" | go tool \
            fleeting-artifact login \
            -username cloudscalech+fleeting \
            -password-stdin
          go tool fleeting-artifact release \
            "quay.io/cloudscalech/fleeting-plugin-cloudscale:$GITHUB_REF_NAME"
        env:
          QUAY_IO_TOKEN: ${{ secrets.QUAY_IO_TOKEN}}
